language: R
sudo: required
cache: packages
warnings_are_errors: false
latex: false
r_check_args: --as-cran

matrix:
  include:
    - os: linux
      r: release
    - os: linux
      r: devel

notifications:
  email:
    on_success: change
    on_failure: change
