language: R
sudo: required
cache: packages
warnings_are_errors: false
latex: false
r_check_args: --as-cran

r_github_packages: jchiquet/rggm

matrix:
  include:
    - os: osx
      r: release
    - os: linux
      r: devel
    - os: linux
      r: release
      r_packages:
        - pkgdown
      after_success:
        - R CMD INSTALL .
        - Rscript -e 'pkgdown::build_site()'
      deploy:
        - provider: pages
          skip-cleanup: true
          github-token: $GITHUB_JANINE
          keep-history: true
          local-dir: docs
          on:
            branch: master

notifications:
  email:
    on_success: change
    on_failure: change
